line-length = 100
target-version = "py310"

[lint]
select = [
    "E",
    "F",
    "I",
    "UP",
    "B"
]
ignore = [
    "E501",
    "B008",
    "B904",
    "F403",
    "E402",
    "E722",
    "B006",
    "F401",
    "B007",
    "E741",
    "F821",
    "F811",
    "UP035"
]
