"""Add tenant_id

Revision ID: 9dfe93eb3e61
Revises: 95a925f68c10
Create Date: 2026-06-21 07:43:00.290743

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9dfe93eb3e61"
down_revision: str | Sequence[str] | None = "95a925f68c10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "tenant_memberships",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_ref_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_ref_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenant_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tenant_memberships_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tenant_memberships_tenant_ref_id"), ["tenant_ref_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tenant_memberships_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "departments",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("business_unit_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_unit_id"],
            ["business_units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_departments_business_unit_id"), ["business_unit_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_departments_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("ad_computers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_ad_computers_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("ad_domains", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_ad_domains_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("ad_groups", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_ad_groups_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("ad_organizational_units", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_ad_organizational_units_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("ad_trust_relationships", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_ad_trust_relationships_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("ad_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_ad_users_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_alerts_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("analytics_asset_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_analytics_asset_profiles_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("analytics_priorities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_analytics_priorities_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("analytics_recommendations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_analytics_recommendations_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("analytics_risk_scores", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_analytics_risk_scores_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("analytics_trend_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_analytics_trend_data_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("anomalies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_anomalies_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("asset_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_asset_history_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("asset_relationships", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_asset_relationships_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("asset_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_asset_snapshots_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("asset_tags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_asset_tags_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_assets_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("automation_alerts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_automation_alerts_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("automation_change_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_automation_change_events_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("automation_jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_automation_jobs_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("automation_schedules", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_automation_schedules_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("automation_workflow_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_automation_workflow_runs_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("behavior_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_behavior_profiles_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("business_services", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_business_services_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("business_units", schema=None) as batch_op:
        batch_op.add_column(sa.Column("organization_id", sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_business_units_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_business_units_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_foreign_key(None, "organizations", ["organization_id"], ["id"])
        batch_op.drop_column("timestamp")
        batch_op.drop_column("owner")

    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_campaigns_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_cases_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_certificates_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("cipher_suites", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_cipher_suites_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("cloud_accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_cloud_accounts_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("cloud_assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_cloud_assets_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("cloud_container_findings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_cloud_container_findings_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("cloud_container_images", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_cloud_container_images_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("cloud_deployments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_cloud_deployments_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("cloud_kubernetes_clusters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_cloud_kubernetes_clusters_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("cloud_namespaces", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_cloud_namespaces_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("cloud_pods", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_cloud_pods_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("cloud_resources", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_cloud_resources_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("cluster_maps", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_cluster_maps_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("cms", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_cms_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("compliance_mappings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_compliance_mappings_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("content_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_content_items_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("controls", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_controls_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("dashboard_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_dashboard_snapshots_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("detection_rules", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_detection_rules_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("dns_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_dns_records_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("endpoints", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_endpoints_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("enrichment_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_enrichment_data_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("enterprise_api_keys", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_enterprise_api_keys_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("enterprise_ownership", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_enterprise_ownership_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("enterprise_permissions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_enterprise_permissions_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("enterprise_roles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_enterprise_roles_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("escalations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_escalations_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("event_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_event_logs_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("event_queue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_event_queue_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("event_rules", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_event_rules_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_evidence_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("executive_reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_executive_reports_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("exposure_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_exposure_profiles_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_findings_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("frameworks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_frameworks_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("graph_edges", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_graph_edges_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("graph_nodes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_graph_nodes_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("graph_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_graph_snapshots_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("http_headers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_http_headers_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_incidents_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("infra_relations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_infra_relations_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("infra_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_infra_snapshots_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("infrastructure_entities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_infrastructure_entities_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("ingestion_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_ingestion_logs_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("intel_cache", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_intel_cache_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("intelligence_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_intelligence_records_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("investigations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_investigations_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("iocs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_iocs_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("k8s_clusters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_k8s_clusters_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("k8s_containers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_k8s_containers_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("k8s_namespaces", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_k8s_namespaces_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("k8s_pods", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_k8s_pods_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("knowledge_base", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_knowledge_base_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("kpis", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_kpis_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_login_attempts_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("osint_emails", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_osint_emails_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("osint_organizations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_osint_organizations_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("osint_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_osint_profiles_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("osint_relationships", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_osint_relationships_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("osint_usernames", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_osint_usernames_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_password_history_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_permissions_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("playbooks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_playbooks_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("plugin_executions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_plugin_executions_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("ports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_ports_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_programs_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("department_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("organization_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_projects_department_id"), ["department_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_projects_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_projects_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_foreign_key(None, "organizations", ["organization_id"], ["id"])
        batch_op.create_foreign_key(None, "departments", ["department_id"], ["id"])

    with op.batch_alter_table("report_evidence", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_report_evidence_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("report_exports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_report_exports_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("report_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_report_records_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("report_scan_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_report_scan_history_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("report_templates", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_report_templates_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_reports_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("reputation_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_reputation_profiles_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("risk_register", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_risk_register_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("role_permissions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_role_permissions_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_roles_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("routes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_routes_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_scans_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("scheduled_reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_scheduled_reports_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("screenshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_screenshots_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("security_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_security_events_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("service_mesh_edges", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_service_mesh_edges_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_services_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("smb_configurations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_smb_configurations_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("smb_groups", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_smb_groups_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("smb_hosts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_smb_hosts_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("smb_password_policies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_smb_password_policies_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("smb_shares", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_smb_shares_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("smb_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_smb_users_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("soar_task_executions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_soar_task_executions_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_targets_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("technologies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_technologies_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column("billing_plan", sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_tenants_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("threat_actors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_threat_actors_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("threat_cache", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_threat_cache_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("threat_links", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_threat_links_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("threat_matches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_threat_matches_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("tls_configurations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_tls_configurations_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("topology_maps", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_topology_maps_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("traffic_communications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_traffic_communications_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("traffic_dns_queries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_traffic_dns_queries_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("traffic_flows", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_traffic_flows_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("traffic_http_metadata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_traffic_http_metadata_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("traffic_protocols", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_traffic_protocols_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("traffic_statistics", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_traffic_statistics_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("traffic_tls_metadata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_traffic_tls_metadata_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_user_roles_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("virtual_hosts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_virtual_hosts_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("visual_graphs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_visual_graphs_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("vuln_cpes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_vuln_cpes_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("vuln_cves", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_vuln_cves_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("vuln_evidence", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_vuln_evidence_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("vuln_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_vuln_records_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("vuln_references", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_vuln_references_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("vuln_risk_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_vuln_risk_profiles_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("vulnerability_signals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_vulnerability_signals_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("wafs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_wafs_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("workflow_executions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_workflow_executions_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_workflows_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("workloads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_workloads_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workloads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workloads_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflows_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("workflow_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_executions_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("wafs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wafs_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("vulnerability_signals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vulnerability_signals_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("vuln_risk_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vuln_risk_profiles_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("vuln_references", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vuln_references_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("vuln_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vuln_records_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("vuln_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vuln_evidence_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("vuln_cves", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vuln_cves_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("vuln_cpes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vuln_cpes_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("visual_graphs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_visual_graphs_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("virtual_hosts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_virtual_hosts_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_roles_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("traffic_tls_metadata", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traffic_tls_metadata_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("traffic_statistics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traffic_statistics_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("traffic_protocols", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traffic_protocols_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("traffic_http_metadata", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traffic_http_metadata_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("traffic_flows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traffic_flows_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("traffic_dns_queries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traffic_dns_queries_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("traffic_communications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traffic_communications_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("topology_maps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topology_maps_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("tls_configurations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tls_configurations_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("threat_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_threat_matches_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("threat_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_threat_links_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("threat_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_threat_cache_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("threat_actors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_threat_actors_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenants_tenant_id"))
        batch_op.drop_column("tenant_id")
        batch_op.drop_column("billing_plan")
        batch_op.drop_column("status")

    with op.batch_alter_table("technologies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_technologies_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_targets_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("soar_task_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_soar_task_executions_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("smb_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_smb_users_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("smb_shares", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_smb_shares_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("smb_password_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_smb_password_policies_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("smb_hosts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_smb_hosts_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("smb_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_smb_groups_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("smb_configurations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_smb_configurations_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_services_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("service_mesh_edges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_service_mesh_edges_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("security_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_security_events_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("screenshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_screenshots_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("scheduled_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduled_reports_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scans_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("routes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_routes_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("role_permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_permissions_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("risk_register", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_register_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("reputation_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reputation_profiles_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("report_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_templates_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("report_scan_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_scan_history_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("report_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_records_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("report_exports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_exports_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("report_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_evidence_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_projects_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_projects_organization_id"))
        batch_op.drop_index(batch_op.f("ix_projects_department_id"))
        batch_op.drop_column("tenant_id")
        batch_op.drop_column("organization_id")
        batch_op.drop_column("department_id")

    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_programs_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("ports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ports_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("plugin_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plugin_executions_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("playbooks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playbooks_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permissions_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_history_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("osint_usernames", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_osint_usernames_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("osint_relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_osint_relationships_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("osint_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_osint_profiles_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("osint_organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_osint_organizations_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("osint_emails", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_osint_emails_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempts_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("kpis", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kpis_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("knowledge_base", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_base_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("k8s_pods", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_k8s_pods_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("k8s_namespaces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_k8s_namespaces_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("k8s_containers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_k8s_containers_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("k8s_clusters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_k8s_clusters_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("iocs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_iocs_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("investigations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investigations_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("intelligence_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_intelligence_records_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("intel_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_intel_cache_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("ingestion_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingestion_logs_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("infrastructure_entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_infrastructure_entities_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("infra_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_infra_snapshots_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("infra_relations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_infra_relations_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incidents_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("http_headers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_http_headers_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("graph_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_snapshots_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("graph_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_nodes_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("graph_edges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_edges_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("frameworks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_frameworks_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_findings_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("exposure_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exposure_profiles_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("executive_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_executive_reports_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("event_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_rules_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("event_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_queue_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("event_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_logs_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("escalations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_escalations_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("enterprise_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enterprise_roles_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("enterprise_permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enterprise_permissions_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("enterprise_ownership", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enterprise_ownership_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("enterprise_api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enterprise_api_keys_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("enrichment_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enrichment_data_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("endpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_endpoints_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("dns_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dns_records_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("detection_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_detection_rules_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("dashboard_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dashboard_snapshots_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("controls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_controls_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("content_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_items_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("compliance_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_compliance_mappings_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cms_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cluster_maps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cluster_maps_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cloud_resources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cloud_resources_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cloud_pods", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cloud_pods_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cloud_namespaces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cloud_namespaces_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cloud_kubernetes_clusters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cloud_kubernetes_clusters_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cloud_deployments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cloud_deployments_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cloud_container_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cloud_container_images_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cloud_container_findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cloud_container_findings_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cloud_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cloud_assets_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cloud_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cloud_accounts_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cipher_suites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cipher_suites_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_certificates_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaigns_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("business_units", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner", sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column("timestamp", sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_business_units_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_business_units_organization_id"))
        batch_op.drop_column("tenant_id")
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("business_services", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_business_services_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("behavior_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_behavior_profiles_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("automation_workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_workflow_runs_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("automation_schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_schedules_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("automation_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_jobs_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("automation_change_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_change_events_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("automation_alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_alerts_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("asset_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_tags_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("asset_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_snapshots_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("asset_relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_relationships_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("asset_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_history_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("anomalies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_anomalies_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("analytics_trend_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analytics_trend_data_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("analytics_risk_scores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analytics_risk_scores_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("analytics_recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analytics_recommendations_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("analytics_priorities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analytics_priorities_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("analytics_asset_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analytics_asset_profiles_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("ad_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ad_users_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("ad_trust_relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ad_trust_relationships_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("ad_organizational_units", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ad_organizational_units_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("ad_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ad_groups_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("ad_domains", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ad_domains_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("ad_computers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ad_computers_tenant_id"))
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_departments_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_departments_business_unit_id"))

    op.drop_table("departments")
    with op.batch_alter_table("tenant_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_tenant_memberships_tenant_ref_id"))
        batch_op.drop_index(batch_op.f("ix_tenant_memberships_tenant_id"))

    op.drop_table("tenant_memberships")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_tenant_id"))

    op.drop_table("organizations")
    # ### end Alembic commands ###
